.TH keyring 1 "Date: 2005/03/01 01:00:00" "Wizard's Toolkit"
.SH NAME
keyring \- 
.SH SYNOPSIS
.TP
\fBkeyring\fP [\fIoptions\fP ...] [\fIkeyring\fP ...]  keyring.rdf

\fBkeyring\fP [\fIoptions\fP ...] -export id [\fIkeyring\fP ...] keyring.xdm
.SH OVERVIEW
\fBKeyring\fP imports, exports, list properties of keys in your keyring.

For more information about the keyring command, point your browser to file:///usr/share/doc/WizardsToolkit-1/www/keyring.html or http://www.wizards-toolkit.org/script/keyring.php.
.SH DESCRIPTION
  -debug events        display copious debugging information
  -export id           export a key from your keyring
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information
.SH SEE-ALSO
WizardsToolkit(1)

.SH COPYRIGHT

\fBCopyright (C) 1999-2012 ImageMagick Studio LLC. Additional copyrights and licenses apply to this software, see file:///usr/share/doc/WizardsToolkit-1/www/license.php or http://www.wizards-toolkit.org/script/license.php\fP
