WizardsToolkit: blob.h File Reference
blob.h File Reference
#include "wizard/exception.h"
Defines
#define WizardMaxBufferExtent 0x3c005L
Typedefs
typedef struct _BlobInfo BlobInfo
Enumerations
enum MapMode { ReadMode, WriteMode, IOMode }
Functions
WizardExport unsigned char * FileToBlob (const char *, const size_t, size_t *, ExceptionInfo *)
WizardExport void * MapBlob (int, const MapMode, const WizardOffsetType, const size_t)
WizardExport WizardBooleanType UnmapBlob (void *, const size_t)
Define Documentation
#define WizardMaxBufferExtent 0x3c005L
Referenced by FileToBlob(), and ReadFileChunk().
Typedef Documentation
typedef struct _BlobInfo BlobInfo
Enumeration Type Documentation
enum MapMode
Enumerator:
ReadMode
WriteMode
IOMode
Function Documentation
WizardExport unsigned char* FileToBlob (const char * , const size_t, size_t * , ExceptionInfo *)
References AcquireQuantumMemory(), BlobError, close, fileno, GetWizardModule, LogWizardEvent(), MapBlob(), MaxCipherBlocksize, Min, O_BINARY, open, read, ReadMode, RelinquishWizardMemory(), ResizeQuantumMemory(), SSIZE_MAX, ThrowWizardException(), TraceEvent, UnmapBlob(), WizardMaxBufferExtent, and WizardSeek.
Referenced by FileToString(), and FileToStringInfo().
WizardExport void* MapBlob (int , const MapMode, const WizardOffsetType, const size_t)
References IOMode, mmap, PROT_READ, ReadMode, and WriteMode.
Referenced by ConfigureFileToStringInfo(), FileToBlob(), OpenBlob(), and SetBlobExtent().
WizardExport WizardBooleanType UnmapBlob (void * , const size_t)
References munmap, WizardFalse, and WizardTrue.
Referenced by ConfigureFileToStringInfo(), DestroyBlob(), DestroyWizardMemory(), DetachBlob(), FileToBlob(), and SetBlobExtent().