WizardsToolkit: bzip.h File Reference
bzip.h File Reference
Typedefs
typedef struct _BZIPInfo BZIPInfo
Functions
WizardExport BZIPInfo * AcquireBZIPInfo (const size_t)
WizardExport BZIPInfo ** DestroyBZIPInfo (BZIPInfo *)
WizardExport const StringInfo * GetBZIPChaos (const BZIPInfo *)
WizardExport WizardBooleanType IncreaseBZIP (BZIPInfo *, const StringInfo *, ExceptionInfo *)
WizardExport WizardBooleanType RestoreBZIP (BZIPInfo *, const size_t, const StringInfo *, ExceptionInfo *)
Typedef Documentation
typedef struct _BZIPInfo BZIPInfo
Function Documentation
WizardExport BZIPInfo* AcquireBZIPInfo (const size_t)
WizardExport BZIPInfo* * DestroyBZIPInfo (BZIPInfo *)
References _BZIPInfo::chaos, DestroyStringInfo(), EntropyDomain, GetWizardModule, LogWizardEvent(), RelinquishWizardMemory(), _BZIPInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by DestroyEntropyInfo().
WizardExport const StringInfo* GetBZIPChaos (const BZIPInfo *)
References _BZIPInfo::chaos, EntropyDomain, GetWizardModule, LogWizardEvent(), _BZIPInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by GetEntropyChaos().
WizardExport WizardBooleanType IncreaseBZIP (BZIPInfo * , const StringInfo * , ExceptionInfo *)
WizardExport WizardBooleanType RestoreBZIP (BZIPInfo * , const size_t, const StringInfo * , ExceptionInfo *)
References _BZIPInfo::chaos, EntropyDomain, GetStringInfoDatum(), GetStringInfoLength(), GetWizardModule, LogWizardEvent(), SetStringInfoLength(), _BZIPInfo::signature, ThrowWizardException(), TraceEvent, WizardAssert, WizardFalse, WizardSignature, and WizardTrue.
Referenced by RestoreEntropy().