WizardsToolkit: client.c File Reference
client.c File Reference
#include "wizard/studio.h"
#include "wizard/client.h"
#include "wizard/string_.h"
Functions
WizardExport const char * GetClientName (void)
WizardExport const char * GetClientPath (void)
WizardExport const char * SetClientName (const char *name)
WizardExport const char * SetClientPath (const char *path)
Function Documentation
WizardExport const char* GetClientName (void)
References SetClientName().
Referenced by DefaultErrorHandler(), DefaultFatalErrorHandler(), DefaultWarningHandler(), TranslateEvent(), and TranslateFilename().
WizardExport const char* GetClientPath (void)
References SetClientPath().
Referenced by GetConfigurePaths().
WizardExport const char* SetClientName (const char * name)
References CopyWizardString(), and MaxTextExtent.
Referenced by GetClientName(), and WizardsToolkitGenesis().
WizardExport const char* SetClientPath (const char * path)
References CopyWizardString(), and MaxTextExtent.
Referenced by GetClientPath(), and WizardsToolkitGenesis().