WizardsToolkit: client.h File Reference
client.h File Reference
Functions
WizardExport const char * GetClientPath (void)
WizardExport const char ** GetClientName (void)
WizardExport const char *** SetClientName (const char *)
WizardExport const char **** SetClientPath (const char *)
Function Documentation
WizardExport const char* * GetClientName (void)
WizardExport const char* GetClientPath (void)
WizardExport const char* * * SetClientName (const char *)
WizardExport const char* * * * SetClientPath (const char *)
References CopyWizardString(), and MaxTextExtent.
Referenced by GetClientPath(), and WizardsToolkitGenesis().