WizardsToolkit: magick.c File Reference
magick.c File Reference
#include "wizard/studio.h"
#include "wizard/hash.h"
#include "wizard/magick.h"
#include "wizard/string_.h"
Functions
WizardExport StringInfo * GetWizardMagick (const unsigned char *signature, const size_t length)
Variables
unsigned char MagickWizard [4]
unsigned char WizardMagick [4]
Function Documentation
WizardExport StringInfo* GetWizardMagick (const unsigned char * signature, const size_t length)
References AcquireHashInfo(), AcquireStringInfo(), CloneStringInfo(), DestroyHashInfo(), DestroyStringInfo(), FinalizeHash(), GetHashDigest(), InitializeHash(), SetStringInfoDatum(), SHA256Hash, and UpdateHash().
Referenced by ExportKeyringKey(), GetEntropyFromReservoir(), ImportKeyringKey(), PrintKeyringProperties(), and SaveEntropyToReservoir().
Variable Documentation
unsigned char MagickWizard[4]
Initial value:
  {
    (unsigned char) 0x45,
                (unsigned char) 0x45,
    (unsigned char) 0x53,
    (unsigned char) 0x7f
  }
unsigned char WizardMagick
Initial value:
        {
          (unsigned char) 0x7f,
                (unsigned char) 0x53,
                (unsigned char) 0x45,
                (unsigned char) 0x45
  }
Referenced by ExportKeyringKey(), GetEntropyFromReservoir(), ImportKeyringKey(), PrintKeyringProperties(), and SaveEntropyToReservoir().