WizardsToolkit: passphrase.h File Reference
passphrase.h File Reference
Functions
WizardExport StringInfo * GetPassphrase (ExceptionInfo *exception)
Function Documentation
WizardExport StringInfo* GetPassphrase (ExceptionInfo * exception)
References AcquireStringInfo(), CompareStringInfo(), DestroyStringInfo(), EchoOffMode, FormatWizardString(), GetPhrase(), GetStringInfoLength(), GetWizardModule, MaxTextExtent, PrintWizardString(), SetStringInfoLength(), STDERR_FILENO, ThrowWizardException(), WizardFalse, and write.
Referenced by AuthenticateSecretKey(), and GenerateSecretKey().