WizardsToolkit: sha1.h File Reference
sha1.h File Reference
Typedefs
typedef struct _SHA1Info SHA1Info
Functions
WizardExport SHA1Info * AcquireSHA1Info (void)
WizardExport SHA1Info ** DestroySHA1Info (SHA1Info *)
WizardExport const StringInfo * GetSHA1Digest (const SHA1Info *)
WizardExport unsigned int GetSHA1Blocksize (const SHA1Info *)
WizardExport unsigned int GetSHA1Digestsize (const SHA1Info *)
WizardExport void InitializeSHA1 (SHA1Info *)
WizardExport void FinalizeSHA1 (SHA1Info *)
WizardExport void UpdateSHA1 (SHA1Info *, const StringInfo *)
Typedef Documentation
typedef struct _SHA1Info SHA1Info
Function Documentation
WizardExport SHA1Info* AcquireSHA1Info (void)
WizardExport SHA1Info* * DestroySHA1Info (SHA1Info *)
References _SHA1Info::accumulator, DestroyStringInfo(), _SHA1Info::digest, GetWizardModule, LogWizardEvent(), _SHA1Info::message, RelinquishWizardMemory(), _SHA1Info::signature, TraceEvent, and WizardSignature.
Referenced by DestroyHashInfo().
WizardExport void FinalizeSHA1 (SHA1Info *)
WizardExport unsigned int GetSHA1Blocksize (const SHA1Info *)
WizardExport const StringInfo* GetSHA1Digest (const SHA1Info *)
References _SHA1Info::digest, GetWizardModule, HashDomain, LogWizardEvent(), _SHA1Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by FinalizeHash().
WizardExport unsigned int GetSHA1Digestsize (const SHA1Info *)
References CipherDomain, _SHA1Info::digestsize, GetWizardModule, LogWizardEvent(), _SHA1Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by AcquireHashInfo(), and GetHashDigestsize().
WizardExport void InitializeSHA1 (SHA1Info *)
WizardExport void UpdateSHA1 (SHA1Info * , const StringInfo *)
References CopyWizardMemory(), GetStringInfoDatum(), GetStringInfoLength(), _SHA1Info::high_order, _SHA1Info::low_order, _SHA1Info::message, _SHA1Info::offset, SetStringInfoDatum(), _SHA1Info::signature, TransformSHA1(), Trunc32(), and WizardSignature.
Referenced by UpdateHash().