WizardsToolkit: sha256.h File Reference
sha256.h File Reference
Typedefs
typedef struct _SHA256Info SHA256Info
Functions
WizardExport SHA256Info * AcquireSHA256Info (void)
WizardExport SHA256Info ** DestroySHA256Info (SHA256Info *)
WizardExport const StringInfo * GetSHA256Digest (const SHA256Info *)
WizardExport unsigned int GetSHA256Blocksize (const SHA256Info *)
WizardExport unsigned int GetSHA256Digestsize (const SHA256Info *)
WizardExport void InitializeSHA256 (SHA256Info *)
WizardExport void FinalizeSHA256 (SHA256Info *)
WizardExport void UpdateSHA256 (SHA256Info *, const StringInfo *)
Typedef Documentation
typedef struct _SHA256Info SHA256Info
Function Documentation
WizardExport SHA256Info* AcquireSHA256Info (void)
WizardExport SHA256Info* * DestroySHA256Info (SHA256Info *)
References _SHA256Info::accumulator, DestroyStringInfo(), _SHA256Info::digest, GetWizardModule, LogWizardEvent(), _SHA256Info::message, RelinquishWizardMemory(), _SHA256Info::signature, TraceEvent, and WizardSignature.
Referenced by DestroyHashInfo().
WizardExport void FinalizeSHA256 (SHA256Info *)
WizardExport unsigned int GetSHA256Blocksize (const SHA256Info *)
WizardExport const StringInfo* GetSHA256Digest (const SHA256Info *)
References _SHA256Info::digest, GetWizardModule, HashDomain, LogWizardEvent(), _SHA256Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by FinalizeHash().
WizardExport unsigned int GetSHA256Digestsize (const SHA256Info *)
References CipherDomain, _SHA256Info::digestsize, GetWizardModule, LogWizardEvent(), _SHA256Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by AcquireHashInfo(), and GetHashDigestsize().
WizardExport void InitializeSHA256 (SHA256Info *)
WizardExport void UpdateSHA256 (SHA256Info * , const StringInfo *)
References CopyWizardMemory(), GetStringInfoDatum(), GetStringInfoLength(), _SHA256Info::high_order, _SHA256Info::low_order, _SHA256Info::message, _SHA256Info::offset, SetStringInfoDatum(), _SHA256Info::signature, TransformSHA256(), Trunc32(), and WizardSignature.
Referenced by UpdateHash().