WizardsToolkit: sha384.h File Reference
sha384.h File Reference
Typedefs
typedef struct _SHA384Info SHA384Info
Functions
WizardExport SHA384Info * AcquireSHA384Info (void)
WizardExport SHA384Info ** DestroySHA384Info (SHA384Info *)
WizardExport const StringInfo * GetSHA384Digest (const SHA384Info *)
WizardExport unsigned int GetSHA384Blocksize (const SHA384Info *)
WizardExport unsigned int GetSHA384Digestsize (const SHA384Info *)
WizardExport void InitializeSHA384 (SHA384Info *)
WizardExport void FinalizeSHA384 (SHA384Info *)
WizardExport void UpdateSHA384 (SHA384Info *, const StringInfo *)
Typedef Documentation
typedef struct _SHA384Info SHA384Info
Function Documentation
WizardExport SHA384Info* AcquireSHA384Info (void)
WizardExport SHA384Info* * DestroySHA384Info (SHA384Info *)
References _SHA384Info::accumulator, DestroyStringInfo(), _SHA384Info::digest, GetWizardModule, LogWizardEvent(), _SHA384Info::message, RelinquishWizardMemory(), _SHA384Info::signature, TraceEvent, and WizardSignature.
Referenced by DestroyHashInfo().
WizardExport void FinalizeSHA384 (SHA384Info *)
WizardExport unsigned int GetSHA384Blocksize (const SHA384Info *)
WizardExport const StringInfo* GetSHA384Digest (const SHA384Info *)
References _SHA384Info::digest, GetWizardModule, HashDomain, LogWizardEvent(), _SHA384Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by FinalizeHash().
WizardExport unsigned int GetSHA384Digestsize (const SHA384Info *)
References CipherDomain, _SHA384Info::digestsize, GetWizardModule, LogWizardEvent(), _SHA384Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by AcquireHashInfo(), and GetHashDigestsize().
WizardExport void InitializeSHA384 (SHA384Info *)
WizardExport void UpdateSHA384 (SHA384Info * , const StringInfo *)
References CopyWizardMemory(), GetStringInfoDatum(), GetStringInfoLength(), _SHA384Info::high_order, _SHA384Info::low_order, _SHA384Info::message, _SHA384Info::offset, SetStringInfoDatum(), _SHA384Info::signature, TransformSHA384(), Trunc64(), and WizardSignature.
Referenced by UpdateHash().