WizardsToolkit: sha512.h File Reference
sha512.h File Reference
Typedefs
typedef struct _SHA512Info SHA512Info
Functions
WizardExport SHA512Info * AcquireSHA512Info (void)
WizardExport SHA512Info ** DestroySHA512Info (SHA512Info *)
WizardExport const StringInfo * GetSHA512Digest (const SHA512Info *)
WizardExport unsigned int GetSHA512Blocksize (const SHA512Info *)
WizardExport unsigned int GetSHA512Digestsize (const SHA512Info *)
WizardExport void InitializeSHA512 (SHA512Info *)
WizardExport void FinalizeSHA512 (SHA512Info *)
WizardExport void UpdateSHA512 (SHA512Info *, const StringInfo *)
Typedef Documentation
typedef struct _SHA512Info SHA512Info
Function Documentation
WizardExport SHA512Info* AcquireSHA512Info (void)
WizardExport SHA512Info* * DestroySHA512Info (SHA512Info *)
References _SHA512Info::accumulator, DestroyStringInfo(), _SHA512Info::digest, GetWizardModule, LogWizardEvent(), _SHA512Info::message, RelinquishWizardMemory(), _SHA512Info::signature, TraceEvent, and WizardSignature.
Referenced by DestroyHashInfo().
WizardExport void FinalizeSHA512 (SHA512Info *)
WizardExport unsigned int GetSHA512Blocksize (const SHA512Info *)
WizardExport const StringInfo* GetSHA512Digest (const SHA512Info *)
References _SHA512Info::digest, GetWizardModule, HashDomain, LogWizardEvent(), _SHA512Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by FinalizeHash().
WizardExport unsigned int GetSHA512Digestsize (const SHA512Info *)
References CipherDomain, _SHA512Info::digestsize, GetWizardModule, LogWizardEvent(), _SHA512Info::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by AcquireHashInfo(), and GetHashDigestsize().
WizardExport void InitializeSHA512 (SHA512Info *)
WizardExport void UpdateSHA512 (SHA512Info * , const StringInfo *)
References CopyWizardMemory(), GetStringInfoDatum(), GetStringInfoLength(), _SHA512Info::high_order, _SHA512Info::low_order, _SHA512Info::message, _SHA512Info::offset, SetStringInfoDatum(), _SHA512Info::signature, TransformSHA512(), Trunc64(), and WizardSignature.
Referenced by UpdateHash().