WizardsToolkit: token.c File Reference
token.c File Reference
#include "wizard/studio.h"
#include "wizard/exception.h"
#include "wizard/exception-private.h"
#include "wizard/string_.h"
#include "wizard/token.h"
#include "wizard/utility.h"
Data Structures
struct _TokenInfo
Functions
WizardExport void GetWizardToken (const char *start, const char **end, char *token)
WizardExport WizardBooleanType GlobExpression (const char *expression, const char *pattern, const WizardBooleanType case_insensitive)
WizardExport WizardBooleanType IsGlob (const char *path)
Function Documentation
WizardExport void GetWizardToken (const char * start, const char ** end, char * token)
References CopyWizardString(), DirectorySeparator, LocaleNCompare(), and WizardPathExtent.
Referenced by LoadLogList().
WizardExport WizardBooleanType GlobExpression (const char * expression, const char * pattern, const WizardBooleanType case_insensitive)
References LocaleCompare(), WizardFalse, and WizardTrue.
Referenced by GetConfigureInfoList(), GetConfigureList(), GetLogInfoList(), GetLogList(), GetMimeInfo(), GetMimeInfoList(), and GetMimeList().
WizardExport WizardBooleanType IsGlob (const char * path)
References IsAccessible(), WizardFalse, and WizardTrue.