WizardsToolkit: token.h File Reference
token.h File Reference
Typedefs
typedef struct _TokenInfo TokenInfo
Functions
WizardExport int Tokenizer (TokenInfo *, unsigned, char *, size_t, char *, char *, char *, char *, char, char *, int *, char *)
WizardExport WizardBooleanType GlobExpression (const char *, const char *, const WizardBooleanType)
WizardExport WizardBooleanType IsGlob (const char *)
WizardExport void GetWizardToken (const char *, const char **, char *)
Typedef Documentation
typedef struct _TokenInfo TokenInfo
Function Documentation
WizardExport void GetWizardToken (const char * , const char ** , char *)
References CopyWizardString(), DirectorySeparator, LocaleNCompare(), and MaxTextExtent.
Referenced by LoadLogList().
WizardExport WizardBooleanType GlobExpression (const char * , const char * , const WizardBooleanType)
WizardExport WizardBooleanType IsGlob (const char *)
References IsAccessible(), WizardFalse, and WizardTrue.
WizardExport int Tokenizer (TokenInfo * , unsigned , char * , size_t , char * , char * , char * , char * , char , char * , int * , char *)