WizardsToolkit: twofish.h File Reference
twofish.h File Reference
Typedefs
typedef struct _TwofishInfo TwofishInfo
Functions
WizardExport TwofishInfo * AcquireTwofishInfo (void)
WizardExport TwofishInfo ** DestroyTwofishInfo (TwofishInfo *)
WizardExport unsigned int GetTwofishBlocksize (const TwofishInfo *)
WizardExport void DecipherTwofishBlock (TwofishInfo *, const unsigned char *, unsigned char *)
WizardExport void EncipherTwofishBlock (TwofishInfo *, const unsigned char *, unsigned char *)
WizardExport void SetTwofishKey (TwofishInfo *, const StringInfo *)
Typedef Documentation
typedef struct _TwofishInfo TwofishInfo
Function Documentation
WizardExport TwofishInfo* AcquireTwofishInfo (void)
WizardExport void DecipherTwofishBlock (TwofishInfo * , const unsigned char * , unsigned char *)
WizardExport TwofishInfo* * DestroyTwofishInfo (TwofishInfo *)
References CipherDomain, GetWizardModule, LogWizardEvent(), RelinquishWizardMemory(), _TwofishInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by DestroyCipherInfo().
WizardExport void EncipherTwofishBlock (TwofishInfo * , const unsigned char * , unsigned char *)
WizardExport unsigned int GetTwofishBlocksize (const TwofishInfo *)
References _TwofishInfo::blocksize, CipherDomain, GetWizardModule, LogWizardEvent(), _TwofishInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by AcquireCipherInfo().
WizardExport void SetTwofishKey (TwofishInfo * , const StringInfo *)
References CipherDomain, GetStringInfoDatum(), GetStringInfoLength(), GetWizardModule, K128, K192, K256, LogWizardEvent(), MaximumTwofishKeyLength, Min, ResetWizardMemory(), _TwofishInfo::sbox, Sbox, _TwofishInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by SetCipherKey().