WizardsToolkit: wizard.h File Reference
wizard.h File Reference
Functions
WizardExport void WizardsToolkitTerminus (void)
WizardExport void WizardsToolkitGenesis (const char *)
Function Documentation
WizardExport void WizardsToolkitGenesis (const char *)
References ConfigureComponentGenesis(), CopyWizardString(), GetEnvironmentValue(), GetExecutionPath(), GetPathComponent(), HeadPath, instantiate_wizardstoolkit, IsEventLogging(), LockWizardMutex(), LogComponentGenesis(), MaxTextExtent, MimeComponentGenesis(), RandomComponentGenesis(), RegisterWizardSignalHandler(), RelinquishWizardMemory(), ResourceComponentGenesis(), SemaphoreComponentGenesis(), SetClientName(), SetClientPath(), SetLogEventMask(), signal_handlers, TailPath, UnlockWizardMutex(), and WizardFalse.
WizardExport void WizardsToolkitTerminus (void)