WizardsToolkit: zip.h File Reference
zip.h File Reference
Typedefs
typedef struct _ZIPInfo ZIPInfo
Functions
WizardExport const StringInfo * GetZIPChaos (const ZIPInfo *)
WizardExport WizardBooleanType IncreaseZIP (ZIPInfo *, const StringInfo *, ExceptionInfo *)
WizardExport WizardBooleanType RestoreZIP (ZIPInfo *, const size_t, const StringInfo *, ExceptionInfo *)
WizardExport ZIPInfo * AcquireZIPInfo (const size_t)
WizardExport ZIPInfo ** DestroyZIPInfo (ZIPInfo *)
Typedef Documentation
typedef struct _ZIPInfo ZIPInfo
Function Documentation
WizardExport ZIPInfo* AcquireZIPInfo (const size_t)
WizardExport ZIPInfo* * DestroyZIPInfo (ZIPInfo *)
References _ZIPInfo::chaos, DestroyStringInfo(), EntropyDomain, GetWizardModule, LogWizardEvent(), RelinquishWizardMemory(), _ZIPInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by DestroyEntropyInfo().
WizardExport const StringInfo* GetZIPChaos (const ZIPInfo *)
References _ZIPInfo::chaos, EntropyDomain, GetWizardModule, LogWizardEvent(), _ZIPInfo::signature, TraceEvent, WizardAssert, and WizardSignature.
Referenced by GetEntropyChaos().
WizardExport WizardBooleanType IncreaseZIP (ZIPInfo * , const StringInfo * , ExceptionInfo *)
WizardExport WizardBooleanType RestoreZIP (ZIPInfo * , const size_t, const StringInfo * , ExceptionInfo *)
References _ZIPInfo::chaos, EntropyDomain, GetStringInfoDatum(), GetStringInfoLength(), GetWizardModule, LogWizardEvent(), SetStringInfoLength(), _ZIPInfo::signature, ThrowWizardException(), TraceEvent, WizardAssert, WizardFalse, WizardSignature, and WizardTrue.
Referenced by RestoreEntropy().